export const INCREMENT_COUNT = "INCREMENT_COUNT";
export const DECREMENT_COUNT = "DECREMENT_COUNT";
export const ADD_GROCERY_ITEM = "ADD_GROCERY_ITEM";
export const REMOVE_GROCERY_ITEM = "REMOVE_GROCERY_ITEM";

export const ADD_TO_CART = "ADD_TO_CART";
export const CLEAR_FROM_CART = "CLEAR_FROM_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const SET_ON_BOARDED = "SET_ON_BOARDED";
export const PRICE_CHANGE='PRICE_CHANGE';
export const SET_FAVOURITE='SET_FAVOURITE';
export const REMOVE_FAVOURITE='REMOVE_FAVOURITE';


// // SIGN UP
// export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
// export const SIGNUP_ERROR = "SIGNUP_ERROR";

// // SIGN IN
// export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
// export const SIGNIN_ERROR = "SIGNIN_ERROR";
// export const EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED";

// // SIGN OUT
// export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
// export const SIGNOUT_ERROR = "SIGNOUT_ERROR";

// // RESET PASSWORD
// export const RESET_SUCCESS = "RESET_SUCCESS";
// export const RESET_ERROR = "RESET_ERROR";